### PR TITLE
Remove upper case transformations from GA

### PR DESCRIPTION
**Pull request by danielvangelder**
GA transformed table and column names to upper case names which would cause trouble in unit test generation. Removing this feature does not seem to cause any trouble for Sqlfpc or jSQLparser (for which it was intended). See #29 for details.

### CODE REVIEW

**Comment by pvdstel** [comment]
Currently, the following three tests take way longer to execute than they used to:
- realQueryBasedOnErpnextQ1016P19
- testStringFunctionsReverse
- refrigeratorReverse

I'm not sure what causes it, but we should look into this.

**Comment by pvdstel** [comment]
An update to my own concerns about the test speed regression: it appears that the tests run as fast as ever when using CLI tools such as Gradle to run the test. It mostly seems that the new IntelliJ 2018.1 release is slowing things down.

While checking this out, Gradle generated 321735 log lines in a timespan of `86.063` seconds when running unit tests in `StringsTest.java`. Some tests in IDEA did not even finish, and the whole testing process seemed to take longer for the tests that _did_ finish. Perhaps some new instrumentation was added to the new release that makes the test performance drop a bit. I don't think this is a blocking issue however.

**Comment by mauricioaniche** [comment]
Wow, @danielvangelder, this is a lot of work. Thanks for this PR!

Just for me to understand the motives: why the upper case would cause problems to the test generation?

**Comment by pvdstel** [comment]
We started testing using a simple PostgreSQL server, since that's a nice free SQL DBMS that supports escaping via quotes (`"`). This was necessary since the SqlSecurer class escapes all identifiers (table and column names) with quotes. This is probably necessary since SQLFpc doesn't like MySQL syntax with the backticks (`` ` ``). Also, we both think it's good to escape identifiers but that's beside the point.

Now, what happened is that we created a schema in Postgres that was using camelCase for identifiers. SQL is usually case-insensitive, but once you start escaping identifiers, the DBMS suddenly decides that it should now be case-sensitive, and then this becomes an issue.

To illustrate; we have a table named `demoTest`. Whether you use `DEMOTEST` or `demotest` does not matter. However, EvoSQL currently transforms these identifiers into `"DEMOTEST"` which does not exist in a case-sensitive system. This made Postgres spit out all kinds of nasty errors. We figured not making identifiers upper case would be preferable to having the user update their database schema to uppercase notation :wink:

**Comment by mauricioaniche** [comment]
Makes totally sense to me!

**Pull request merged**
